name: 自动更新
on:
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:
env:
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    ZONE_ID: ${{ secrets.ZONE_ID }}

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: 准备仓库文件
              uses: actions/checkout@v2

            - name: 准备Python
              uses: actions/setup-python@main
              with:
                python-version: '3.11'

            - name: 安装依赖
              run: |
                pip install -r requirements.txt

            - name: 设置环境变量
              run: |
                echo "BASE_PATH=$(pwd)" >> $GITHUB_ENV
                echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

            - name: 运行检查
              run: |
                python get.py

            - name: 同步index.html
              run: |
                git fetch origin main
                git checkout origin/main -- index.html

            - name: 提交更改
              run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                git checkout -B stats
                git add cloudflare_hourly_stats.json index.html
                git commit -m "Update cloudflare_hourly_stats.json and sync index.html"
                git push -f origin stats